### ISSUE TITLE
ln(sp) vs sp in GG/SH files

### ISSUE THREAD

**Issue by pabretonniere** [goord/ece2cmor3#21] opened 2017-04-24 16:12 UTC
Hi @goord ,

CMORizing our files from the latest EC-Earth version, it fails because it is looking for the surface pressure in the SH files to calculate the levels. It is due to the commit 3842 (https://dev.ec-earth.org/projects/ecearth3/repository/revisions/3842) that you made in the primavera branch saying to output the pressure level in the GG files and not in the SH as before (keeping only lnsp in the SH). 
I can update the code to tell ece2cmor to compute the levels from exp(ln(sp)) but I wanted to check if you hadn't already had the same problem. I think we would lose less information than using ps from the GG files.

Thanks,
Cheers,

**Comment by goord** [comment] 2017-04-24 18:51
Hi Pierre-Antoine,

I noticed this too when I was doing the cmorization at ecmwf. I can commit my changes and then ece2cmor3 will just query the GG file for the surface pressure. Perhaps the best solution would be to add an option to ece2cmor3 to tell it where to look for ps, because it may be in either file...

**Comment by etiennesky** [comment] 2017-04-25 08:14
Hi @goord I am not sure that using sp from the  GG file since the grid is not the same as the one in the SH file. 
I think that ece2cmor3 should compute sp on the fly from exp(lnsp) if sp is not found, without any option.

Etienne

**Comment by etiennesky** [comment] 2017-04-25 08:52
So according to @pabretonniere sp must be present in the SH files before sending them to cmor library, which would require a pre-processing step with grib_filter.

Would it not be simpler then to simply re-add sp to the IFS output in the SS files ?

Also is lnsp used at all, in which case we could remove it in favor of sp?

**Comment by klauswyser** [comment] 2017-04-25 08:55
Indeed, sp in the GG file and sp in the ICMSH file are not the same beast, but honestly I cannot tell which one is correct and which one isn’t. There are a few fundamental differences between the two:

- lnsp in the ICMSH file is the logarithm of the surface pressure in **spectral** representation. When doing sp2spl the inverse fourier transformation is applied to evaluate the field in the gridpoints of a **regular** Gauss grid, before taking the exponential. The surface to which this surface pressure corresponds to is the spectral orography that is different from the real orography. The spectral orography is a smooth representation of the real orography and in regions with strong vartical varaition we see traces of the Gibbs phenomena, e.g. in the Pacific Ocean along the Chilean coast.
- sp in the ICMGG field is a gridpoint representation on the **reduced** Gauss grid. There is a **linear(?) interpolation** to go from the reduced to the regular Gauss grid, although we know that pressure doesn't vary linearly with altitude.

Clearly, the two surface pressures are not the same, and I would say it depends on the application to say which one is more appropriate. For working with upper air fields I probably woud take lnsp from ICMSH, but for working with SFC data I'd rather had the gridpoint value from ICMGG. Which one should we save for CMIP6?

BTW: whatever ps we decide to save should also have an implication on which orography we are delivering to CMIP6, SFC pressure and orography should correspond to each other.

**Comment by etiennesky** [comment] 2017-04-25 09:05
I think that the cmor library requires sp in the SH files, so this question is about where do we get sp from, the GG files (I think better not), exp(lnsp), or add them to the SH files from IFS.

in the openIFS doc on IFS output (https://software.ecmwf.int/wiki/display/OIFS/How+to+control+OpenIFS+output), there is a hint that sp, lnsp and shold be enabled, which are not at the moment.

**Comment by klauswyser** [comment] 2017-04-25 09:08
Can you save sp (134) in ICMSH? I thought you can only save lnsp (151)  there, but I may be wrong.

**Comment by etiennesky** [comment] 2017-04-25 09:08
And then there if the quite relevant issue which Klaus also raised, do we get sp from SH of GG files for final output ? What was done in cmip5/specs ?

**Comment by etiennesky** [comment] 2017-04-25 09:15
Yes Klaus saving sp(134) is possible but it was removed by Gijs some time ago in r3842 "Moved surface pressure (134) from MFP2DF to gridpoint variables".

Also Z(129) was removed in r3844,  "Removed 129 from 2d spectral variables, already produced on gridpoints".

I am not sure I understand why these were removed, perhaps this did not do what was intended.

**Comment by goord** [comment] 2017-04-25 09:20
If you enable 134 in the MFP2DF namelist, it will appear in the spectral file, if you add it to the MFPPHY namelist it appears in the gridpoint file. Note there are several use cases: 3D fields need hybrid model level information to be stored within the same netcdf file, for this CMOR needs sp, some variables need to be calculated during postprocessing and need the surface pressure for this, and finally we need to report sp in various tables.

**Comment by goord** [comment] 2017-04-25 09:27
Etienne, in https://software.ecmwf.int/wiki/display/OIFS/How+to+control+OpenIFS+output they also mention you can output them on gridpts, I thought it didn't matter since we are converting to gridpoints anyway...

**Comment by klauswyser** [comment] 2017-04-25 09:32
> it didn't matter since we are converting to gridpoints anyway...

It does because they are not equal in gridpoint space.

@etiennesky: spectral orography would be good to have, but only in ICMSH*+000000 (similar as gridpoint orography is svaed only in ICMGG*+000000)

**Comment by goord** [comment] 2017-04-25 09:41
Ok, so can I summarize this as follows:

1) For the reconstruction of the hybrid model levels, we should exponentiate lnsp (or use sp) in the spectral representation, this will give the best result along the entire vertical range.
2) For the computation of certain surface fields, we can use sp in the gridpoint file (this is actually necessary in ece2cmor3, it cannot combine variables from the two files)
3) For the mean surface pressure, requested in some of the tables, the spectral version is a better match with the orography

**Comment by pabretonniere** [comment] 2017-04-25 15:14
OK, so, in the end, we agree that the easiest (and less memory intensive) option would be to output directly from the model sp both in the GG and SH files, right?

**Comment by etiennesky** [comment] 2017-04-25 15:56
@pabretonniere and I think that it would be much more efficient to save sp in the SH files, instead of computing it at the beginning of ece2cmor3 which will further add to the processing time at a small cost of space. This way it is available for other computations by cmor library, as well as for the output consistent with spectral orography.  

Do you guys agree?

I can  add spectral orography  to the ICMSH*+000000 and sp to the 3h and 6h files in the primavera branch and have @pabretonniere test again.

**Comment by goord** [comment] 2017-04-26 10:46
Yes that is a good idea, it would also be useful to test the differences between the spectral and gridpoint surface pressure fields after interpolation upon the regular grid. Note that we have to keep ps also in the GG file to calculate the surface specific humidity.

I can make ece2cmor in such a way that it look for sp in the SH file, and if not found, looks for lnsp and exponentiates it. This is not too much overhead since it is just a surface field, the 3d fields dominate the runtime anyway.

**Comment by etiennesky** [comment] 2017-04-27 09:26
OK, I will add sp to the SH files and make sure that the orography is present in both SH and GG initial state files (just the first timestep) .

However, do we still need lnsp in both SH and GG files?

**Comment by goord** [comment] 2017-04-27 10:56
No, if sp is in there we don't need lnsp, and I think the diagnostics will continue to work if we remove it.

**Comment by etiennesky** [comment] 2017-04-27 13:45
Hi @klauswyser is there any scientific or technical reason why we should save lnsp? If not I will drop it from the output list in favor of sp. Thanks!

**Comment by klauswyser** [comment] 2017-04-27 20:07
- lnsp is considered to be more accurate yet this argument may be outdated nowadays, it was certainly valid with 8-bit packing in GRIB.
- lnsp is more appropriate for doing linear interpolation. If we assume that orography varies linearly between gridpoints, then pressure doesn't vary lineraly, yet lnsp does more or less.

But honestly, I don't think any of these reasons is strong enough to warrant that we save both sp and lnsp in both the ICMGG and the ICMSH file, for simplicity I would just save sp.

**Comment by etiennesky** [comment] 2017-05-08 16:33
I just committed the proposed changes to the primavera branch in r4236 . @pabretonniere needs to test and fix the python grib filter with the files I have after this change.

**Closed** 2017-08-10 13:59 UTC
